### ISSUE TITLE
Can't work will

### ISSUE THREAD

**Issue by mohdeleiwa** [botble/wordpress-importer#3]
I have a website created by WordPress, I export it to XML file to use it on Botlbe5.11 website but I can't import it there is an error after uploading the file.

XML file size is 18291kb.

https://prnt.sc/x8hhw5

Thank you

**Comment by sangnguyenplus** [comment]
@mohdeleiwa Not sure about that error, please check error logs in /storages/logs/laravel-d-m-y.log for more details.
